In [2]:
import numpy as np
import pandas as pd

In [3]:
series=pd.Series([49,43,65,40,160])
series

0     49
1     43
2     65
3     40
4    160
dtype: int64

In [4]:
series.dtype

dtype('int64')

In [5]:
series.name="Pokemon Savunma Güçleri"
series

0     49
1     43
2     65
3     40
4    160
Name: Pokemon Savunma Güçleri, dtype: int64

In [6]:
series.index=["Bulbasaur","Charmander", "Squirtle" ,"Pikachu","Onix"]
series

Bulbasaur      49
Charmander     43
Squirtle       65
Pikachu        40
Onix          160
Name: Pokemon Savunma Güçleri, dtype: int64

In [7]:
pd.Series({"Balbasaur" :49 , "Charmander":43, "Squirtle":65 ,"Pikachu" : 40,"Onix":160})
series

Bulbasaur      49
Charmander     43
Squirtle       65
Pikachu        40
Onix          160
Name: Pokemon Savunma Güçleri, dtype: int64

In [8]:
series["Pikachu"]
series.iloc[3]

np.int64(40)

In [ ]:
series[["Bulbasaur" , "Pikachu"]]
series.iloc[[0,3]]
series["Bulbasaur":"Pikachu"]

Bulbasaur     49
Charmander    43
Squirtle      65
Pikachu       40
Name: Pokemon Savunma Güçleri, dtype: int64

In [ ]:
series>40

Bulbasaur      True
Charmander     True
Squirtle       True
Pikachu       False
Onix           True
Name: Pokemon Savunma Güçleri, dtype: bool

In [ ]:
series[series>40]

Bulbasaur      49
Charmander     43
Squirtle       65
Onix          160
Name: Pokemon Savunma Güçleri, dtype: int64

In [ ]:
series[series>series.mean()]

Onix    160
Name: Pokemon Savunma Güçleri, dtype: int64

In [ ]:
series["Pikachu"]=70
series

Bulbasaur      49
Charmander     43
Squirtle       65
Pikachu        70
Onix          160
Name: Pokemon Savunma Güçleri, dtype: int64

In [ ]:
series[series>series.mean()]=50
series

Bulbasaur     49
Charmander    43
Squirtle      65
Pikachu       70
Onix          50
Name: Pokemon Savunma Güçleri, dtype: int64

In [ ]:
series = pd.Series({ 'Bulbasaur': 49, 'Charmander': 43, 'Squirtle': 65, 'Pikachu': 40, 'Onix': 160 },
name="Pokemon Savunma Güçleri")
series

Bulbasaur      49
Charmander     43
Squirtle       65
Pikachu        40
Onix          160
Name: Pokemon Savunma Güçleri, dtype: int64

In [11]:
pokemon = pd.DataFrame({
'atak': [49, 52, 48, 55, 45], 'savunma': [49, 43, 65, 40, 160], 'hız': [45, 65, 43, 90, 70],
'tür': ['ot', 'ateş', 'su', 'elektrik', 'kaya'] },
index=["Bulbasaur", "Charmander", "Squirtle", "Pikachu", "Onix"])
pokemon

            atak  savunma  hız       tür
Bulbasaur     49       49   45        ot
Charmander    52       43   65      ateş
Squirtle      48       65   43        su
Pikachu       55       40   90  elektrik
Onix          45      160   70      kaya

In [12]:
pokemon.columns
#pokemon.index

Index(['atak', 'savunma', 'hız', 'tür'], dtype='object')

In [ ]:
pokemon.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Bulbasaur to Onix
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   atak     5 non-null      int64
 1   savunma  5 non-null      int64
 2   hız      5 non-null      int64
 3   tür      5 non-null      object
dtypes: int64(3), object(1)
memory usage: 372.0+ bytes

In [13]:
pokemon.size

20

In [ ]:
pokemon.shape

(5, 4)

In [ ]:
pokemon.describe()

            atak     savunma        hız
count   5.000000    5.000000   5.000000
mean   49.800000   71.400000  62.600000
std     3.834058   50.460876  19.398454
min    45.000000   40.000000  43.000000
25%    48.000000   43.000000  45.000000
50%    49.000000   49.000000  65.000000
75%    52.000000   65.000000  70.000000
max    55.000000  160.000000  90.000000

In [ ]:
pokemon["atak"]

Bulbasaur     49
Charmander    52
Squirtle      48
Pikachu       55
Onix          45
Name: atak, dtype: int64

In [ ]:
pokemon.iloc[2] #indexi getirir

atak       48
savunma    65
hız        43
tür        su
Name: Squirtle, dtype: object

In [ ]:
pokemon.loc["Pikachu"]

atak             55
savunma          40
hız              90
tür        elektrik
Name: Pikachu, dtype: object

In [ ]:
pokemon["hız"]>60

Bulbasaur     False
Charmander     True
Squirtle      False
Pikachu        True
Onix           True
Name: hız, dtype: bool

In [ ]:
pokemon[pokemon["hız"]>60]

            atak  savunma  hız       tür
Charmander    52       43   65      ateş
Pikachu       55       40   90  elektrik
Onix          45      160   70      kaya

In [ ]:
pokemon.loc[pokemon["hız"]>60 , "hız"]

Charmander    65
Pikachu       90
Onix          70
Name: hız, dtype: int64

In [ ]:
pokemon.drop("Onix" , inplace=True)
pokemon

            atak  savunma  hız       tür
Bulbasaur     49       49   45        ot
Charmander    52       43   65      ateş
Squirtle      48       65   43        su
Pikachu       55       40   90  elektrik

In [18]:
pokemon.drop("tür" , axis=1)

            atak  savunma  hız
Bulbasaur     49       49   45
Charmander    52       43   65
Squirtle      48       65   43
Pikachu       55       40   90
Onix          45      160   70

In [ ]:
pokemon[["atak" , "savunma"]]/10

            atak  savunma
Bulbasaur    4.9      4.9
Charmander   5.2      4.3
Squirtle     4.8      6.5
Pikachu      5.5      4.0

In [ ]:
pokemon[["atak" , "savunma"]] + [10 , 5]

            atak  savunma
Bulbasaur     59       54
Charmander    62       48
Squirtle      58       70
Pikachu       65       45

In [ ]:
boy=pd.Series([0.7 , 0.6 , 0.5 ,0.4] , index=pokemon.index)
boy

Bulbasaur     0.7
Charmander    0.6
Squirtle      0.5
Pikachu       0.4
dtype: float64

In [ ]:
pokemon["boy"]=boy
pokemon

            atak  savunma  hız       tür  boy
Bulbasaur     49       49   45        ot  0.7
Charmander    52       43   65      ateş  0.6
Squirtle      48       65   43        su  0.5
Pikachu       55       40   90  elektrik  0.4

In [ ]:
pokemon["boy"]=1
pokemon

            atak  savunma  hız       tür  boy
Bulbasaur     49       49   45        ot    1
Charmander    52       43   65      ateş    1
Squirtle      48       65   43        su    1
Pikachu       55       40   90  elektrik    1

In [ ]:
pokemon.rename(columns={"atak":"attack"})

            attack  savunma  hız       tür  boy
Bulbasaur       49       49   45        ot    1
Charmander      52       43   65      ateş    1
Squirtle        48       65   43        su    1
Pikachu         55       40   90  elektrik    1

In [ ]:
pokemon["toplam güç"]=pokemon["atak"]+pokemon["savunma"]+pokemon["hız"]
pokemon

            atak  savunma  hız       tür  boy  toplam güç
Bulbasaur     49       49   45        ot    1         143
Charmander    52       43   65      ateş    1         160
Squirtle      48       65   43        su    1         156
Pikachu       55       40   90  elektrik    1         185

In [36]:
pokemon2 = pd.DataFrame({
'atak': [49, np.nan, 48, np.nan, 45], 'savunma': [np.nan, 43, 65, 40, np.nan], 'hız': [45, 65, 43, 90, 70],
 },
index=["Bulbasaur", "Charmander", "Squirtle", "Pikachu", "Onix"])
pokemon2

            atak  savunma  hız
Bulbasaur   49.0      NaN   45
Charmander   NaN     43.0   65
Squirtle    48.0     65.0   43
Pikachu      NaN     40.0   90
Onix        45.0      NaN   70

In [30]:
pokemon2.dropna()

          atak  savunma  hız tür
Squirtle  48.0     65.0   43  su

In [31]:
pokemon2.isnull()

             atak  savunma    hız    tür
Bulbasaur   False     True  False  False
Charmander   True    False  False  False
Squirtle    False    False  False  False
Pikachu      True    False  False  False
Onix        False     True  False  False

In [32]:
pokemon2.fillna(0)

            atak  savunma  hız       tür
Bulbasaur   49.0      0.0   45        ot
Charmander   0.0     43.0   65      ateş
Squirtle    48.0     65.0   43        su
Pikachu      0.0     40.0   90  elektrik
Onix        45.0      0.0   70      kaya

In [37]:
pokemon2.fillna(pokemon2.mean())

                 atak    savunma  hız
Bulbasaur   49.000000  49.333333   45
Charmander  47.333333  43.000000   65
Squirtle    48.000000  65.000000   43
Pikachu     47.333333  40.000000   90
Onix        45.000000  49.333333   70

In [38]:
pokemon2

            atak  savunma  hız
Bulbasaur   49.0      NaN   45
Charmander   NaN     43.0   65
Squirtle    48.0     65.0   43
Pikachu      NaN     40.0   90
Onix        45.0      NaN   70

In [39]:
pokemon2.fillna(method="ffill")

/tmp/ipython-input-1073295630.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  pokemon2.fillna(method="ffill")

            atak  savunma  hız
Bulbasaur   49.0      NaN   45
Charmander  49.0     43.0   65
Squirtle    48.0     65.0   43
Pikachu     48.0     40.0   90
Onix        45.0     40.0   70

In [40]:
pokemon2.fillna(method="bfill")

/tmp/ipython-input-3665316483.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  pokemon2.fillna(method="bfill")

            atak  savunma  hız
Bulbasaur   49.0     43.0   45
Charmander  48.0     43.0   65
Squirtle    48.0     65.0   43
Pikachu     45.0     40.0   90
Onix        45.0      NaN   70

In [41]:
elciler = pd.Series([ 'France', 'United Kingdom', 'United Kingdom', 'Italy', 'Germany', 'Germany', 'Germany', ], index=[
'Gérard Araud', 'Kim Darroch', 'Peter Westmacott', 'Armando Varricchio', 'Peter Wittig', 'Peter Ammon', 'Klaus Scharioth ' ])
elciler

Gérard Araud                  France
Kim Darroch           United Kingdom
Peter Westmacott      United Kingdom
Armando Varricchio             Italy
Peter Wittig                 Germany
Peter Ammon                  Germany
Klaus Scharioth              Germany
dtype: object

In [42]:
elciler.duplicated()

Gérard Araud          False
Kim Darroch           False
Peter Westmacott       True
Armando Varricchio    False
Peter Wittig          False
Peter Ammon            True
Klaus Scharioth        True
dtype: bool

In [43]:
elciler.drop_duplicates(keep=False)

Gérard Araud          France
Armando Varricchio     Italy
dtype: object

In [44]:
df = pd.DataFrame({ 'Veri': [ '1987_E_ABD _1', '1990?_E_ING_1', '1992_K_ABD_2', '1970?_E_ IT_1', '1985_K_I T_2' ]})
df

            Veri
0  1987_E_ABD _1
1  1990?_E_ING_1
2   1992_K_ABD_2
3  1970?_E_ IT_1
4   1985_K_I T_2

In [46]:
df["Veri"].str.split("_")

0    [1987, E, ABD , 1]
1    [1990?, E, ING, 1]
2     [1992, K, ABD, 2]
3    [1970?, E,  IT, 1]
4     [1985, K, I T, 2]
Name: Veri, dtype: object

In [47]:
df["Veri"].str.split("_" , expand=True)

       0  1     2  3
0   1987  E  ABD   1
1  1990?  E   ING  1
2   1992  K   ABD  2
3  1970?  E    IT  1
4   1985  K   I T  2

In [54]:
df2=df["Veri"].str.split("_" , expand=True)
df2.columns=["Yıl", "Cinsiyet", "Ülke", "Çocuk Sayısı"]
df2

     Yıl Cinsiyet  Ülke Çocuk Sayısı
0   1987        E  ABD             1
1  1990?        E   ING            1
2   1992        K   ABD            2
3  1970?        E    IT            1
4   1985        K   I T            2

In [57]:
df2["Yıl"].str.contains("\?")

<>:1: SyntaxWarning: invalid escape sequence '\?'
<>:1: SyntaxWarning: invalid escape sequence '\?'
/tmp/ipython-input-3924919776.py:1: SyntaxWarning: invalid escape sequence '\?'
  df2["Yıl"].str.contains("\?")

0    False
1     True
2    False
3     True
4    False
Name: Yıl, dtype: bool